### ISSUE TITLE
[Mocha IR] Most 9k scores cannot be uploaded

### ISSUE THREAD

**Issue by Deipnosophy** [exch-bms2/beatoraja#470] opened 2019-09-03 00:48 UTC
Almost all of my song results in PMS/9k mode cannot be uploaded to the Mocha IR. 14k or 7k works with Mocha, and uploading to Minir also works. This happens with Gauge Auto Shift on and off.

The most relevant line in the log seems to be this: `IRスコア送信失敗 : invalid judge count value`. I've attached the full xml log (as a txt extension since Github doesn't support xml files) as well.
[beatoraja_log.txt](https://github.com/exch-bms2/beatoraja/files/3567328/beatoraja_log.txt)

I am using beatoraja 0.7.2 and the Litone5 skin. Example charts that cause this error for me:
- Dance Doll Dream Hyper (not on IR)
- https://mocha-repository.info/song.php?sha256=093d9eb45c3f249712f30fe7d1465d463f31dafd119c01a6d985ca1e0b4df707
- https://mocha-repository.info/song.php?sha256=6b62dcec393d0a964d2335c13b665a9616d34cabf6f8f267ab0171875a9aa552
- https://mocha-repository.info/song.php?sha256=a01a44b21e7621509dad8d9a6caa9028604480b5cd7167b9eeabc3e8fcf3053

Thank you!

**Comment by exch-bms2** [comment] 2019-09-03 13:32
In my environment, score data (AIR hyper Lv.39) is uploaded successfully.

Please check your play options (especially 9key assist mode), and clear/update your song database.

**Comment by Deipnosophy** [comment] 2019-09-03 18:57
I created a fresh Beatoraja install and cleared the database, I am still seeing `invalid judge count value`. My play options are default: ![settings](https://user-images.githubusercontent.com/50883293/64199840-12ca7e00-ce40-11e9-8489-fc9141473a17.png)

Even failing a song causes the error on IR upload, and I tried creating a new IR user, but the same error happens.

I had a few scores in the past like on this song, but replaying it caused the same IR error today: https://mocha-repository.info/song.php?sha256=99ba23c227cf09cb250bee42a85896c82d7d6e37ce40192d8b7c3e4566ff2b71

This is the row for this chart in my songinfo.db song table, everything looks normal to me:
`"58661"	"06abbf52c401e0832930d23e72097a10"	"99ba23c227cf09cb250bee42a85896c82d7d6e37ce40192d8b7c3e4566ff2b71"	"1024[9Keys_EX]"	""	"ピアノアンビエント"	"風鈴奏"	""	""	"C:\LR2beta3\Songs\Insane PMS\1024\[風鈴奏] 1024\1024-9EX.pms"	"92a48f8d"	""	""	"1024_bg.png"	""	"f3615f0a"	"47"	"4"	"100"	"50"	"9"	"3"	"0"	"3"	"1368902154"	"0"	"1024"	"1567523346"	"758867e1aba9bbba773a6ac0a15afa1638d81b84bb2350bef406369a5e7c0bcf"	"116408"`

**Comment by exch-bms2** [comment] 2019-09-05 18:39
Maybe caused by Mocha-Repository API, so I addad a special logger on these APIs.
Please try to re-send 9key scores.

**Comment by Deipnosophy** [comment] 2019-09-05 22:05
I sent a few more 9k scores since your message:
 
- https://mocha-repository.info/song.php?sha256=a836f56c2616cb912a76dd7b4389dc599663a69e0127c55525c7e10be53cf673 my first score was recorded, my second score on this song was not recorded.
- https://mocha-repository.info/song.php?sha256=1b46543b0a2bcd11557f0721425590870597c137f9b168316a5ffca235d7fda6, https://mocha-repository.info/song.php?sha256=7b4f2371928c7c89156707366233beaa17ceb413ffa202e8a361f6860cb8d72e and https://mocha-repository.info/song.php?sha256=561f9810e57be19ce4c32a109ee88a39fe5d20cad90ca8aab702dcefe973c0c9 were not recorded.
- Air hyper level 39 was not recorded either.

Thanks for looking into this issue! Please let me know if I can help you further.

**Comment by exch-bms2** [comment] 2019-09-06 01:38
If possible, could you send your replay data that failed to upload?
Song replay data is here:
./player/(Player directory name. Maybe player1)/replay/(Song SHA256).brd

**Comment by Deipnosophy** [comment] 2019-09-06 02:34
Sure! 
[561f9810e57be19ce4c32a109ee88a39fe5d20cad90ca8aab702dcefe973c0c9.zip](https://github.com/exch-bms2/beatoraja/files/3581973/561f9810e57be19ce4c32a109ee88a39fe5d20cad90ca8aab702dcefe973c0c9.zip)

**Comment by exch-bms2** [comment] 2019-09-06 04:40
Sorry, I can't test this because this chart seems to be unavailable. Can you send other replay or this  chart data? (.pms file)

**Comment by Deipnosophy** [comment] 2019-09-06 16:41
My apologies, I should have checked that the chart is easily available.

Here's another replay for Yakumo Joint Struggle, chart download: http://stellawingroad.web.fc2.com/sabun/yakumo_nu.zip
[b733e77b4495a9498bbe6f22eabbf43b4a4e831b3d8322ca2a50d8bcc34e8a28.zip](https://github.com/exch-bms2/beatoraja/files/3584828/b733e77b4495a9498bbe6f22eabbf43b4a4e831b3d8322ca2a50d8bcc34e8a28.zip)

**Comment by exch-bms2** [comment] 2019-09-06 19:11
Now fixed this problem and close. 
This problem is caused by mocha-API. I misunderstanded 9key judge specification.

In 9key mode, BAD notes are sometimes modified to PGREAT/GREAT/GOOD.  In such cases, [totalnotes < pgreat + great + good + bad + poor].
In other mode, this situation can't happen. Always [totalnotes = pgreat + great + good + bad + poor].
(If failed in the middle, remaining notes are modified to POOR)

**Closed by exch-bms2** 2019-09-06 19:11 UTC

**Comment by Deipnosophy** [comment] 2019-09-06 20:18
Thank you very much!
