### ISSUE TITLE
beatoraja freezes in middle of specific song on mac

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#25] opened 2017-03-23 14:57 UTC
Issue:
beatoraja freezes at TIME 1:36 on this bms:  daisan - 天上のポリスルイン [Hyper]
BMS Download: http://colosseo.nekokan.dyndns.info/c02_shuffle/detail.php?n=9

System Specs:
Computer: Macbook Pro 17-inch 2009 Late
CPU: 3,06 GHz Intel Core 2 Duo
GPU: NVIDIA GeForce 9600M GT 512 MB
RAM: 8 GB 1067 MHz DDR3
Internal storage: SSD Samsung Pro 480GB
OS: 10.11.6 OS X El Capitan
Native Resolution: 1920x1200
beatoraja Resolution: 1280x720

beatoraja version: 0.4

to reproduce: 
Assist Option: CONSTANT
play with Auto

Log:
```
2017-03-23 16:01:39.260 java[56757:386136] 16:01:39.260 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Controllers: added manager for application, 1 managers active
Mar 23, 2017 4:01:41 PM bms.player.beatoraja.skin.Skin prepare
INFO: 描画されないことが確定しているSkinObject削除 : 0 / 102
Mar 23, 2017 4:01:41 PM bms.player.beatoraja.MainController create
INFO: 初期化時間(ms) : 1487

Mar 23, 2017 4:01:48 PM bms.player.beatoraja.skin.Skin prepare
INFO: 描画されないことが確定しているSkinObject削除 : 0 / 5
[mpegvideo @ 0x7fa33585ac00] Estimating duration from bitrate, this may be inaccurate
Input #0, mpegvideo, from '/Users/dan/Documents/dan/Games/Rhythm Games/BMS projects/OTHER BMS/Polis Ruin/PR_BGA.mpg':
  Duration: 00:02:10.00, bitrate: 1149 kb/s
    Stream #0:0: Video: mpeg1video, yuv420p(tv), 256x256 [SAR 1:1 DAR 1:1], 1150 kb/s, 24 fps, 24 tbr, 1200k tbn, 24 tbc
Mar 23, 2017 4:01:49 PM bms.player.beatoraja.play.bga.BGAProcessor setModel
INFO: BGAファイル読み込み完了。BGA数:1
Mar 23, 2017 4:01:51 PM bms.player.beatoraja.play.BMSPlayer <init>
INFO: アシストオプション設定完了
Mar 23, 2017 4:01:51 PM bms.player.beatoraja.play.BMSPlayer <init>
INFO: 譜面オプション :  0
Mar 23, 2017 4:01:51 PM bms.player.beatoraja.play.BMSPlayer <init>
INFO: ゲージ設定完了
Mar 23, 2017 4:01:52 PM bms.player.beatoraja.play.BMSPlayer create
INFO: スコアデータベースからスコア取得
Mar 23, 2017 4:01:52 PM bms.player.beatoraja.skin.Skin prepare
INFO: 描画されないことが確定しているSkinObject削除 : 52 / 94
pause
Mar 23, 2017 4:02:04 PM bms.player.beatoraja.audio.AbstractAudioDriver setModel
INFO: 音源ファイル読み込み完了。音源数:685
Mar 23, 2017 4:02:04 PM bms.player.beatoraja.audio.AbstractAudioDriver$AudioCache disposeOld
INFO: 現在のAudioCache容量 : 684
Mar 23, 2017 4:02:04 PM bms.player.beatoraja.play.bga.BGImageProcessor prepare
INFO: BGAデータの事前Texture化 - BGAデータ数:0 time(ms):0
Mar 23, 2017 4:02:04 PM bms.player.beatoraja.play.BMSPlayer render
INFO: current free memory : 1143MB , disposed : 296MB
Mar 23, 2017 4:02:04 PM bms.player.beatoraja.play.BMSPlayer render
INFO: STATE_READYに移行
Mar 23, 2017 4:02:05 PM bms.player.beatoraja.play.BMSPlayer render
INFO: STATE_PLAYに移行
Mar 23, 2017 4:02:07 PM bms.player.beatoraja.play.bga.FFmpegProcessor$MovieSeekThread run
INFO: decode開始 - fps : 24.0 format : mpegvideo size : 256 x 256 length (frame / time) : 3119 / 129999138
AL lib: (WW) FreeDevice: (0x7fa335d5ea00) Deleting 688 Buffer(s)
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 1070
	at bms.player.beatoraja.play.LaneRenderer.drawLane(Unknown Source)
	at bms.player.beatoraja.play.SkinNote.draw(Unknown Source)
	at bms.player.beatoraja.skin.Skin.drawAllObjects(Unknown Source)
	at bms.player.beatoraja.MainController.render(Unknown Source)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Exception in thread "Thread-13" java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
	at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
	at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.stopSourcesWithBuffer(OpenALAudio.java:194)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALSound.stop(OpenALSound.java:93)
	at bms.player.beatoraja.audio.GdxSoundDriver.stop(Unknown Source)
	at bms.player.beatoraja.audio.GdxSoundDriver.stop(Unknown Source)
	at bms.player.beatoraja.audio.AbstractAudioDriver.play0(Unknown Source)
	at bms.player.beatoraja.audio.AbstractAudioDriver.play(Unknown Source)
	at bms.player.beatoraja.play.BMSPlayer.play(Unknown Source)
	at bms.player.beatoraja.play.JudgeManager.update(Unknown Source)
	at bms.player.beatoraja.play.BMSPlayer$KeyInputThread.run(Unknown Source)
Exception in thread "Thread-12" java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
	at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
	at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.stopSourcesWithBuffer(OpenALAudio.java:194)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALSound.stop(OpenALSound.java:93)
	at bms.player.beatoraja.audio.GdxSoundDriver.stop(Unknown Source)
	at bms.player.beatoraja.audio.GdxSoundDriver.stop(Unknown Source)
	at bms.player.beatoraja.audio.AbstractAudioDriver.play0(Unknown Source)
	at bms.player.beatoraja.audio.AbstractAudioDriver.play(Unknown Source)
	at bms.player.beatoraja.play.BMSPlayer.play(Unknown Source)
	at bms.player.beatoraja.play.BMSPlayer$AutoplayThread.run(Unknown Source)
```

**Comment by exch-bms2** [comment] 2017-03-24 15:17
This problem may be caused by MacOS version or libGDX.  See http://stackoverflow.com/questions/33098495/java-carbon-component-warning-on-runtime-os-x

**Comment by Agrrox** [comment] 2017-03-24 21:27
i think i should try to test it on newest macOS Sierra (10.12.X) as soon as i can partition my disk for additional OS installation.

**Comment by Agrrox** [comment] 2017-04-16 14:18
problem causing this was  Assist Option : CONSTANT

**Comment by TomoAlien** [comment] 2017-04-16 14:44
I can confirm the crash happens on Windows 7 too.
Beatoraja crashes on every song in which a BPM change occurs while Assist Option CONSTANT is enabled.

**Comment by exch-bms2** [comment] 2017-04-16 21:21
I found this problem was caused by process of applying CONSTANT to Long Note. It will be fixed on next release.

**Closed** 2017-05-12 23:02 UTC
